CREATE TABLE estaciones (
  "id" int NOT NULL,
  "estacion" varchar NOT NULL,
  "nombre" varchar,
  "ubicacion" varchar,
  "desde" date,
  "hasta" date,
  "fuente" varchar,
  "longitud" numeric,
  "latitud" numeric,
  PRIMARY KEY ("id")
);

INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (1, '87641', 'AZUL AERO', NULL, NULL, NULL, 'SMN', '-59.883333333598', '-36.8333333331226');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (2, '87750', 'BAHIA BLANCA AERO', NULL, NULL, NULL, 'SMN', '-62.1666666662309', '-38.7333333336355');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (3, '87649', 'BENITO JUAREZ AERO', NULL, NULL, NULL, 'SMN', '-59.7833333334123', '-37.7166666668275');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (4, '87640', 'BOLIVAR AERO', NULL, NULL, NULL, 'SMN', '-61.0666666668831', '-36.2000000000125');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (5, '87683', 'CORONEL PRINGLES AERO', NULL, NULL, NULL, 'SMN', '-61.3333333331467', '-38.0166666665809');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (6, '87637', 'CORONEL SUAREZ AERO', NULL, NULL, NULL, 'SMN', '-61.8833333337189', '-37.4333333331198');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (7, '87648', 'DOLORES AERO', NULL, NULL, NULL, 'SMN', '-57.7333333336478', '-36.3500000000103');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (8, '87571', 'EL PALOMAR AERO', NULL, NULL, NULL, 'SMN', '-58.6000000001273', '-34.60000000035');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (9, '87576', 'EZEIZA AERO', NULL, NULL, NULL, 'SMN', '-58.5333333333368', '-34.8166666666155');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (10, '87548', 'JUNIN AERO', NULL, NULL, NULL, 'SMN', '-60.9166666670537', '-34.5499999996601');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (11, '87593', 'LA PLATA AERO', NULL, NULL, NULL, 'SMN', '-57.8999999997257', '-34.966666666975');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (12, '87563', 'LAS FLORES AERO', NULL, NULL, NULL, 'SMN', '-59.1333333335527', '-36.0333333334409');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (13, '87692', 'MAR DEL PLATA AERO', NULL, NULL, NULL, 'SMN', '-57.5833333329201', '-37.9333333330209');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (14, '87572', 'MARIANO MORENO AERO', NULL, NULL, NULL, 'SMN', '-58.8166666667472', '-34.5499999996601');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (15, '87573', 'MERLO AERO', NULL, NULL, NULL, 'SMN', '-58.7333333337082', '-34.6833333330691');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (16, '87574', 'MORON AERO', NULL, NULL, NULL, 'SMN', '-58.6333333335225', '-34.6666666668685');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (17, '87550', 'NUEVE DE JULIO', NULL, NULL, NULL, 'SMN', '-60.8833333336585', '-35.4500000001242');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (18, '87643', 'OLAVARRIA AERO', NULL, NULL, NULL, 'SMN', '-60.2166666666521', '-36.883333333501');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (19, '87544', 'PEHUAJO AERO', NULL, NULL, NULL, 'SMN', '-61.8999999999674', '-35.8666666668544');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (20, '87679', 'PIGUE AERO', NULL, NULL, NULL, 'SMN', '-62.3833333337491', '-37.5999999999377');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (21, '87596', 'PUNTA INDIO B.A.', NULL, NULL, NULL, 'SMN', '-57.2833333332613', '-35.3666666665766');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (22, '87553', 'SAN FERNANDO', NULL, NULL, NULL, 'SMN', '-58.5833333329805', '-34.4499999996876');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (23, '87569', 'SAN MIGUEL', NULL, NULL, NULL, 'SMN', '-58.7333333337082', '-34.5499999996601');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (24, '87658', 'SANTA TERESITA AERO', NULL, NULL, NULL, 'SMN', '-56.6833333330454', '-36.5500000000509');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (25, '87645', 'TANDIL AERO', NULL, NULL, NULL, 'SMN', '-59.2499999999869', '-37.2333333333584');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (26, '87540', 'TRENQUE LAUQUEN', NULL, NULL, NULL, 'SMN', '-62.7333333330516', '-35.9666666666763');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (27, '87688', 'TRES ARROYOS', NULL, NULL, NULL, 'SMN', '-60.2500000000473', '-38.3333333335904');
INSERT INTO estaciones("id", "estacion", "nombre", "ubicacion", "desde", "hasta", "fuente", "longitud", "latitud") VALUES (28, '87663', 'VILLA GESELL AERO', NULL, NULL, NULL, 'SMN', '-57.0166666669977', '-37.2333333333584');



CREATE TABLE mediciones (
  "id" int NOT NULL,
  "estacion" varchar NOT NULL,
  "fecha" date,
  "tmax" numeric,
  "tmin" numeric,
  "tmedia" numeric,
  "pp_mm" numeric,
  "heliofania" numeric,
  "viento_max_direccion" numeric,
  "viento_max_intensidad" numeric,
  "viento_medi" numeric,
  "temp_rocio_media" numeric,
  "presion_nivel_estacion" numeric,
  "humedad_relativa" numeric,
  "cant_datos_promedio" numeric,
  PRIMARY KEY ("id")
);


INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43517, '87648', '1980-01-01', '26.2', '4.9', NULL, '0', NULL, '2', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43518, '87648', '1980-01-02', '30.1', '11', NULL, '0', NULL, '34', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43519, '87648', '1980-01-03', '27.7', '15.1', NULL, '0', NULL, '14', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43520, '87648', '1980-01-04', '27.4', '9.2', NULL, '0', NULL, '5', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43521, '87648', '1980-01-05', '26.1', '16.5', NULL, '0.3', NULL, '2', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43522, '87648', '1980-01-06', '29.3', '17.9', NULL, '1.1', NULL, '29', '7.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43523, '87648', '1980-01-07', '34', '17.2', NULL, '0', NULL, '34', '17.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43524, '87648', '1980-01-08', '35.2', '14.6', NULL, '0', NULL, '2', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43525, '87648', '1980-01-09', '37.4', '17.6', NULL, '6.6', NULL, '20', '11.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43526, '87648', '1980-01-10', '29.9', '17', NULL, '0', NULL, '16', '5.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43527, '87648', '1980-01-11', '30.4', '10.7', NULL, '0', NULL, '5', '6.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43528, '87648', '1980-01-12', '31.8', '11.8', NULL, '0', NULL, '2', '7.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43529, '87648', '1980-01-13', '31.9', '17.5', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43530, '87648', '1980-01-14', '31', '19.2', NULL, '0', NULL, '5', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43531, '87648', '1980-01-15', '32.7', '20', NULL, '0', NULL, '2', '11.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43532, '87648', '1980-01-16', '33.1', '18.5', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43533, '87648', '1980-01-17', '32.9', '20.4', NULL, '27.1', NULL, '16', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43534, '87648', '1980-01-18', '28.5', '18', NULL, '0', NULL, '20', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43535, '87648', '1980-01-19', '28.2', '16.5', NULL, '0', NULL, '16', '6.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43536, '87648', '1980-01-20', '30.7', '11.1', NULL, '0', NULL, '23', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43537, '87648', '1980-01-21', '36.3', '18', NULL, '0', NULL, '23', '10.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43538, '87648', '1980-01-22', '36.4', '22', NULL, '0', NULL, '34', '13.4', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43539, '87648', '1980-01-23', '31', '17', NULL, '0', NULL, '20', '12.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43540, '87648', '1980-01-24', '22.2', '7.2', NULL, '0', NULL, '23', '10.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43541, '87648', '1980-01-25', '28.6', '8.2', NULL, '0.3', NULL, '36', '12.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43542, '87648', '1980-01-26', '29.9', '18', NULL, '0', NULL, '27', '10.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43543, '87648', '1980-01-27', '25.2', '9.1', NULL, '0', NULL, '16', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43544, '87648', '1980-01-28', '29.1', '4.4', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43545, '87648', '1980-01-29', '33.2', '11.6', NULL, '0', NULL, '34', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43546, '87648', '1980-01-30', '32.3', '16.9', NULL, '0.2', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43547, '87648', '1980-01-31', '28.5', '15.6', NULL, '0', NULL, '14', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43548, '87648', '1980-02-01', '26.2', '4.1', NULL, '0', NULL, '20', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43549, '87648', '1980-02-02', '29.4', '11.5', NULL, '0', NULL, '2', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43550, '87648', '1980-02-03', '33.3', '18', NULL, '8', NULL, '27', '16.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43551, '87648', '1980-02-04', '30.9', '13.4', NULL, '5.1', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43552, '87648', '1980-02-05', '32', '18.4', NULL, '0', NULL, '14', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43553, '87648', '1980-02-06', '30.9', '17.1', NULL, '0', NULL, '29', '11.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43554, '87648', '1980-02-07', '28.6', '10.7', NULL, '0', NULL, '25', '16.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43555, '87648', '1980-02-08', '33.2', '8.6', NULL, '12.3', NULL, '29', '12.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43556, '87648', '1980-02-09', '26.2', '12.5', NULL, '2.9', NULL, '25', '11.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43557, '87648', '1980-02-10', '23.5', '14.4', NULL, '0', NULL, '14', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43558, '87648', '1980-02-11', '30.3', '11.4', NULL, '0', NULL, '34', '12.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43559, '87648', '1980-02-12', '27.7', '17', NULL, '0', NULL, '25', '11.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43560, '87648', '1980-02-13', '30.1', '9.5', NULL, '0', NULL, '5', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43561, '87648', '1980-02-14', '34.2', '14.8', NULL, '0', NULL, '2', '7.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43562, '87648', '1980-02-15', '30.7', '18.8', NULL, '0', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43563, '87648', '1980-02-16', '28.7', '18.1', NULL, '0', NULL, '16', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43564, '87648', '1980-02-17', '25.5', '9.5', NULL, '0', NULL, '14', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43565, '87648', '1980-02-18', '26.6', '8.2', NULL, '0', NULL, '2', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43566, '87648', '1980-02-19', '29.4', '15.2', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43567, '87648', '1980-02-20', '28.8', '16.4', NULL, '0', NULL, '5', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43568, '87648', '1980-02-21', '27.2', '14.5', NULL, '0', NULL, '2', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43569, '87648', '1980-02-22', '26.9', '12', NULL, '0', NULL, '7', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43570, '87648', '1980-02-23', '29.6', '13.5', NULL, '1.9', NULL, '5', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43571, '87648', '1980-02-24', '28.5', '17.6', NULL, '1.6', NULL, '7', '5.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43572, '87648', '1980-02-25', '30.4', '17.9', NULL, '0', NULL, '27', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43573, '87648', '1980-02-26', '33.4', '16.1', NULL, '0', NULL, '27', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43574, '87648', '1980-02-27', '33.9', '18.4', NULL, '0', NULL, '34', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43575, '87648', '1980-02-28', '35.4', '16', NULL, '0', NULL, '34', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43576, '87648', '1980-02-29', '32.6', '17.4', NULL, '0.8', NULL, '25', '10.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43577, '87648', '1980-03-01', '30.5', '18.4', NULL, '0', NULL, '5', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43578, '87648', '1980-03-02', '31.9', '13.5', NULL, '0', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43579, '87648', '1980-03-03', '29.2', '14.1', NULL, '0', NULL, '5', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43580, '87648', '1980-03-04', '26.5', '16', NULL, '11.9', NULL, '2', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43581, '87648', '1980-03-05', '22.8', '17.5', NULL, '4.3', NULL, '27', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43582, '87648', '1980-03-06', '27.6', '13.7', NULL, '0', NULL, '23', '1.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43583, '87648', '1980-03-07', '29.9', '11.4', NULL, '0', NULL, '27', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43584, '87648', '1980-03-08', '30.9', '13.5', NULL, '0', NULL, '29', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43585, '87648', '1980-03-09', '35.3', '19.1', NULL, '5.2', NULL, '29', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43586, '87648', '1980-03-10', '30.2', '11', NULL, '0', NULL, '2', '2.6', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43587, '87648', '1980-03-11', '28.7', '13.1', NULL, '0', NULL, '16', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43588, '87648', '1980-03-12', '30.4', '17.7', NULL, '0', NULL, '18', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43589, '87648', '1980-03-13', '27.9', '15.1', NULL, '0', NULL, '14', '5.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43590, '87648', '1980-03-14', '32.7', '15', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43591, '87648', '1980-03-15', '32.2', '19.8', NULL, '0', NULL, '2', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43592, '87648', '1980-03-16', '34.3', '19', NULL, '0', NULL, '5', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43593, '87648', '1980-03-17', '34.6', '17.6', NULL, '0', NULL, '5', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43594, '87648', '1980-03-18', '36', '20.6', NULL, '0', NULL, '34', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43595, '87648', '1980-03-19', '37.1', '21.4', NULL, '11.4', NULL, '5', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43596, '87648', '1980-03-20', '38.2', '22.1', NULL, '0', NULL, '29', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43597, '87648', '1980-03-21', '36.3', '23', NULL, '18.3', NULL, '34', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43598, '87648', '1980-03-22', '30.8', '18.9', NULL, '38.7', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43599, '87648', '1980-03-23', '22.8', '17.8', NULL, '10.2', NULL, '2', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43600, '87648', '1980-03-24', '26.2', '18.6', NULL, '0', NULL, '29', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43601, '87648', '1980-03-25', '26.4', '16.5', NULL, '0', NULL, '5', '5.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43602, '87648', '1980-03-26', '28.1', '13.5', NULL, '0', NULL, '2', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43603, '87648', '1980-03-27', '27.7', '18.3', NULL, '0', NULL, '14', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43604, '87648', '1980-03-28', '29.9', '18', NULL, '2.2', NULL, '34', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43605, '87648', '1980-03-29', '22.9', '11.6', NULL, '0', NULL, '18', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43606, '87648', '1980-03-30', '21.6', '5.5', NULL, '1', NULL, '7', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43607, '87648', '1980-03-31', '25.6', '12.1', NULL, '0', NULL, '5', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43608, '87648', '1980-04-01', '25.8', '14.7', NULL, '0', NULL, '2', '7.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43609, '87648', '1980-04-02', '25.1', '18.5', NULL, '0', NULL, '5', '12.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43610, '87648', '1980-04-03', '25.1', '19.7', NULL, '0', NULL, '2', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43611, '87648', '1980-04-04', '25.1', '17.1', NULL, '0.5', NULL, '18', '1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43612, '87648', '1980-04-05', '24.5', '18', NULL, '0', NULL, '18', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43613, '87648', '1980-04-06', '28.2', '16.6', NULL, '0.3', NULL, '0', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43614, '87648', '1980-04-07', '26.4', '17.2', NULL, '0', NULL, '2', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43615, '87648', '1980-04-08', '24.5', '20', NULL, '16.6', NULL, '5', '2.6', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43616, '87648', '1980-04-09', '22.3', '14.6', NULL, '20', NULL, '16', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43617, '87648', '1980-04-10', '20.6', '14.6', NULL, '24.6', NULL, '16', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43618, '87648', '1980-04-11', '18.9', '14.3', NULL, '0', NULL, '20', '8.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43619, '87648', '1980-04-12', '16.3', '5.8', NULL, '0', NULL, '25', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43620, '87648', '1980-04-13', '15.8', '4', NULL, '0', NULL, '27', '11.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43621, '87648', '1980-04-14', '15.1', '2.3', NULL, '0', NULL, '25', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43622, '87648', '1980-04-15', '18.5', '0.6', NULL, '0', NULL, '23', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43623, '87648', '1980-04-16', '17.1', '0.8', NULL, '0', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43624, '87648', '1980-04-17', '23.2', '10.2', NULL, '0', NULL, '32', '12.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43625, '87648', '1980-04-18', '20.8', '3.2', NULL, '0', NULL, '7', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43626, '87648', '1980-04-19', '20', '12', NULL, '0', NULL, '7', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43627, '87648', '1980-04-20', '21.3', '12.9', NULL, '12.9', NULL, '7', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43628, '87648', '1980-04-21', '20.3', '16.7', NULL, '84.1', NULL, '2', '10.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43629, '87648', '1980-04-22', '27.6', '17.4', NULL, '1.2', NULL, '20', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43630, '87648', '1980-04-23', '23.3', '15.8', NULL, '65', NULL, '11', '13.4', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43631, '87648', '1980-04-24', '20.1', '14.7', NULL, '20.5', NULL, '7', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43632, '87648', '1980-04-25', '26.3', '14.8', NULL, '1', NULL, '2', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43633, '87648', '1980-04-26', '28.2', '19.4', NULL, '4', NULL, '2', '5.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43634, '87648', '1980-04-27', '25.9', '18.5', NULL, '6', NULL, '2', '6.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43635, '87648', '1980-04-28', '24.3', '18.4', NULL, '0', NULL, '7', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43636, '87648', '1980-04-29', '23.9', '11.7', NULL, '34.8', NULL, '18', '13.9', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43637, '87648', '1980-04-30', '14.3', '9.3', NULL, '0', NULL, '23', '11.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43638, '87648', '1980-05-01', '14.8', '8', NULL, '0', NULL, '18', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43639, '87648', '1980-05-02', '13.7', '9', NULL, '0.4', NULL, '18', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43640, '87648', '1980-05-03', '16.5', '10', NULL, '0', NULL, '18', '8.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43641, '87648', '1980-05-04', '15.8', '9.4', NULL, '0', NULL, '23', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43642, '87648', '1980-05-05', '17.2', '8.7', NULL, '2.5', NULL, '25', '10.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43643, '87648', '1980-05-06', '15.7', '10.9', NULL, '0', NULL, '25', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43644, '87648', '1980-05-07', '14.1', '8.6', NULL, '0', NULL, '27', '2.6', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43645, '87648', '1980-05-08', '17.8', '8.9', NULL, '0', NULL, '5', '4.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43646, '87648', '1980-05-09', '17.9', '12.7', NULL, '8.8', NULL, '5', '3.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43647, '87648', '1980-05-10', '18.2', '12', NULL, '0', NULL, '25', '1.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43648, '87648', '1980-05-11', '18.2', '11.5', NULL, '0', NULL, '5', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43649, '87648', '1980-05-12', '24.8', '16.2', NULL, '0.9', NULL, '36', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43650, '87648', '1980-05-13', '24.3', '20.9', NULL, '43.4', NULL, '29', '11.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43651, '87648', '1980-05-14', '22.9', '19.8', NULL, '62.7', NULL, '11', '9.3', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43652, '87648', '1980-05-15', '20.7', '15', NULL, '0', NULL, '18', '7.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43653, '87648', '1980-05-16', '16.2', '11.4', NULL, '0', NULL, '2', '2.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43654, '87648', '1980-05-17', '16.3', '10.8', NULL, '0', NULL, '34', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43655, '87648', '1980-05-18', '19.3', '12', NULL, '0', NULL, '36', '2.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43656, '87648', '1980-05-19', '17.7', '15', NULL, '0.4', NULL, '9', '3.1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43657, '87648', '1980-05-20', '18.1', '15.8', NULL, '0.9', NULL, '5', '2.6', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43658, '87648', '1980-05-21', '18', '16.5', NULL, '0', NULL, '18', '7.7', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43659, '87648', '1980-05-22', '19.1', '11', NULL, '0', NULL, '25', '1.5', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43660, '87648', '1980-05-23', '21.1', '14.4', NULL, '0', NULL, '2', '9.8', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43661, '87648', '1980-05-24', '18.9', '12.8', NULL, '0', NULL, '18', '6.2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43662, '87648', '1980-05-25', '17.5', '9.2', '13.9', '0', NULL, '5', '5.1', '2.2', NULL, NULL, '85', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43663, '87648', '1980-05-26', '19.8', '10.8', '16.8', '0', NULL, '2', '2.6', '1.9', NULL, NULL, '93', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43664, '87648', '1980-05-27', '20.1', '14.6', '17.8', '6.3', NULL, '32', '9.8', '5', NULL, NULL, '88', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43665, '87648', '1980-05-28', '17.5', '9.4', '12.5', '0', NULL, '25', '9.8', '3.4', NULL, NULL, '66', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43666, '87648', '1980-05-29', '12.9', '9.1', '11.7', '8', NULL, '7', '1', '0.9', NULL, NULL, '90', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43667, '87648', '1980-05-30', '14.7', '10.4', '12.8', '0', NULL, '18', '0.5', '0.2', NULL, NULL, '95', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43668, '87648', '1980-05-31', '14', '9.8', '11.5', '0', NULL, '2', '9.8', '6.9', NULL, NULL, '82', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43669, '87648', '1980-06-01', '11.3', '7.2', '8.7', '0', NULL, '23', '10.3', '7.2', NULL, NULL, '81', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43670, '87648', '1980-06-02', '10.2', '5.1', '6.8', '0.1', NULL, '25', '13.9', '7.2', NULL, NULL, '84', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43671, '87648', '1980-06-03', '9.6', '2.2', '5.7', '0', NULL, '25', '9.8', '4.8', NULL, NULL, '81', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43672, '87648', '1980-06-04', '9.9', '1.2', '5.9', '0', NULL, '36', '6.2', '4.5', NULL, NULL, '74', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43673, '87648', '1980-06-05', '12.1', '4.9', '8.2', '0', NULL, '32', '7.2', '3.4', NULL, NULL, '82', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43674, '87648', '1980-06-06', '14.8', '4.8', '10.8', '2.1', NULL, '5', '1.5', '0.5', NULL, NULL, '93', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43675, '87648', '1980-06-07', '15.3', '6.5', '13.7', '1.5', NULL, '5', '2.6', '1.9', NULL, NULL, '94', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43676, '87648', '1980-06-08', '17.7', '12.1', '15.9', '8.8', NULL, '34', '6.2', '2.1', NULL, NULL, '95', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43677, '87648', '1980-06-09', '17.6', '12', '13.4', '0', NULL, '18', '6.2', '1.9', NULL, NULL, '85', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43678, '87648', '1980-06-10', '13.3', '10.6', '11.7', '0', NULL, '16', '5.1', '3.9', NULL, NULL, '80', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43679, '87648', '1980-06-11', '13.5', '9', '11.5', '0', NULL, '14', '1', '0.5', NULL, NULL, '93', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43680, '87648', '1980-06-12', '12.4', '9.2', '12', '27', NULL, '16', '5.7', '2.6', NULL, NULL, '99', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43681, '87648', '1980-06-13', '13.2', '9.8', '10.8', '0', NULL, '20', '10.8', '6.2', NULL, NULL, '83', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43682, '87648', '1980-06-14', '13.3', '6', '10.2', '0', NULL, '29', '4.1', '2.2', NULL, NULL, '85', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43683, '87648', '1980-06-15', '14.1', '6.6', '11.2', '0', NULL, '34', '9.8', '6.3', NULL, NULL, '87', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43684, '87648', '1980-06-16', '14.3', '7.4', '11.4', '0', NULL, '27', '5.1', '2.1', NULL, NULL, '91', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43685, '87648', '1980-06-17', '17.3', '4.6', '13.1', '0.5', NULL, '36', '6.2', '3.1', NULL, NULL, '94', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43686, '87648', '1980-06-18', '15.2', '11', '12.9', '0', NULL, '18', '5.1', '4.3', NULL, NULL, '70', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43687, '87648', '1980-06-19', '10.7', '2.6', '6.6', '0', NULL, '16', '2.1', '0.9', NULL, NULL, '76', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43688, '87648', '1980-06-20', '12.3', '1.2', '8.1', '0', NULL, '5', '4.1', '1.4', NULL, NULL, '86', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43689, '87648', '1980-06-21', '14.8', '7.9', '11', '0', NULL, '2', '5.7', '4.3', NULL, NULL, '87', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43690, '87648', '1980-06-22', '16.3', '8.6', '12.4', '0', NULL, '36', '1.5', '1.2', NULL, NULL, '89', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43691, '87648', '1980-06-23', '15.8', '8.6', '13.5', '19', NULL, '2', '5.1', '3.9', NULL, NULL, '87', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43692, '87648', '1980-06-24', '12.9', '8.2', '10.3', '8.4', NULL, '18', '11.8', '6.9', NULL, NULL, '92', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43693, '87648', '1980-06-25', '11.5', '4.1', '7.3', '0', NULL, '23', '8.2', '3.4', NULL, NULL, '78', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43694, '87648', '1980-06-26', '9.6', '3.4', '6.3', '0', NULL, '20', '8.2', '3.8', NULL, NULL, '77', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43695, '87648', '1980-06-27', '10.7', '3.4', '7.9', '0', NULL, '34', '11.8', '6.2', NULL, NULL, '78', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43696, '87648', '1980-06-28', '13.2', '4.1', '9', '0', NULL, '34', '7.2', '1.9', NULL, NULL, '82', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43697, '87648', '1980-06-29', '12.3', '3.8', '8.7', '0.5', NULL, '14', '3.6', '2.7', NULL, NULL, '86', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43698, '87648', '1980-06-30', '9.6', '5.2', '6.8', '0', NULL, '18', '5.1', '3.4', NULL, NULL, '81', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43699, '87648', '1980-07-01', '8.3', '0.2', '4.6', '0', NULL, '20', '5.1', '3.1', NULL, NULL, '85', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43700, '87648', '1980-07-02', '8.9', '0.4', '4.5', '0', NULL, '25', '2.6', '1.2', NULL, NULL, '78', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43701, '87648', '1980-07-03', '9.3', '-1.3', '4.5', '0', NULL, '36', '3.1', '1.9', NULL, NULL, '86', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43702, '87648', '1980-07-04', '13.3', '1.8', '8.1', '0', NULL, '34', '1', '0.3', NULL, NULL, '89', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43703, '87648', '1980-07-05', '14', '3.8', '10.9', '5', NULL, '7', '1.5', '1.2', NULL, NULL, '93', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43704, '87648', '1980-07-06', '12.5', '8.5', '11.6', '0', NULL, '5', '4.1', '3.3', NULL, NULL, '97', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43705, '87648', '1980-07-07', '14.4', '11.1', '12.6', '4.6', NULL, '27', '11.8', '4.5', NULL, NULL, '97', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43706, '87648', '1980-07-08', '10.4', '8.4', '9.5', '0', NULL, '29', '12.9', '9.6', NULL, NULL, '89', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43707, '87648', '1980-07-09', '13', '7.8', '10.5', '0', NULL, '23', '12.3', '4.5', NULL, NULL, '84', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43708, '87648', '1980-07-10', '14.4', '5', '10', '0', NULL, '32', '5.1', '3.3', NULL, NULL, '79', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43709, '87648', '1980-07-11', '14.6', '6.1', '10.3', '0', NULL, '32', '7.2', '5', NULL, NULL, '81', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43710, '87648', '1980-07-12', '15.2', '3.5', '10.3', '0', NULL, '36', '6.2', '3.8', NULL, NULL, '85', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43711, '87648', '1980-07-13', '12.3', '4.2', '9.1', '0', NULL, '20', '10.3', '5.7', NULL, NULL, '83', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43712, '87648', '1980-07-14', '7.5', '0.8', '4.7', '0', NULL, '23', '12.3', '9.9', NULL, NULL, '73', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43713, '87648', '1980-07-15', '8.9', '0.3', '5.5', '0', NULL, '34', '9.3', '7.4', NULL, NULL, '77', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43714, '87648', '1980-07-16', '10.9', '2.2', '6.4', '0', NULL, '36', '2.1', '1.2', NULL, NULL, '86', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43715, '87648', '1980-07-17', '14.1', '0.6', '8.6', '0', NULL, '11', '5.1', '2.6', NULL, NULL, '82', NULL);
INSERT INTO mediciones("id", "estacion", "fecha", "tmax", "tmin", "tmedia", "pp_mm", "heliofania", "viento_max_direccion", "viento_max_intensidad", "viento_medi", "temp_rocio_media", "presion_nivel_estacion", "humedad_relativa", "cant_datos_promedio") VALUES (43716, '87648', '1980-07-18', '14.8', '3.1', '11.8', '2.4', NULL, '5', '6.2', '5.1', NULL, NULL, '85', NULL);
