# Generated by Django 4.1.7 on 2023-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
