# Generated by Django 4.1.7 on 2023-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_project_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('fuente', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estacion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('tmax', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tmin', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tmedia', models.DecimalField(decimal_places=3, max_digits=5)),
                ('pp_mm', models.DecimalField(decimal_places=3, max_digits=7)),
                ('heliofania', models.DecimalField(decimal_places=6, max_digits=10)),
                ('viento_max_direccion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('viento_max_intensidad', models.DecimalField(decimal_places=3, max_digits=5)),
                ('viento_medi', models.DecimalField(decimal_places=3, max_digits=5)),
                ('temp_rocio_media', models.DecimalField(decimal_places=3, max_digits=5)),
                ('presion_nivel_estacion', models.DecimalField(decimal_places=5, max_digits=10)),
                ('humedad_relativa', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cant_datos_promedio', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
