# Generated by Django 4.1.7 on 2023-03-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_estacion_ubicacion_alter_estacion_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
