# Generated by Django 4.1.7 on 2023-03-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_estacion_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='fuente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
