# Generated by Django 4.1.7 on 2023-03-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_estacion_fuente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estacion',
        ),
    ]
