# Generated by Django 4.1.7 on 2023-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_estacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
            ],
        ),
    ]
