# Generated by Django 4.1.7 on 2023-03-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_estacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estacion',
        ),
        migrations.DeleteModel(
            name='Medicion',
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
