# Generated by Django 4.1.7 on 2023-03-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0014_delete_estacion_delete_medicion_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('desde', models.DateField(blank=True, null=True)),
                ('hasta', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tmax', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('tmin', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('tmedia', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('pp_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('heliofania', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('viento_max_direccion', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('viento_max_intensidad', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('viento_medi', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('temp_rocio_media', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('presion_nivel_estacion', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('humedad_relativa', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cant_datos_promedio', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
    ]
