# Generated by Django 4.1.7 on 2023-03-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_medicion_estacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='estacion_id',
            field=models.CharField(default='o', max_length=100),
        ),
    ]
