# Generated by Django 4.1.7 on 2023-03-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_medicion_estacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='estacion_id',
        ),
    ]
