# Generated by Django 4.1.7 on 2023-03-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_medicion_estacion_medicion_id_estacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='id_estacion',
        ),
        migrations.AddField(
            model_name='medicion',
            name='estacion',
            field=models.CharField(default='0000', max_length=100),
        ),
        migrations.AddField(
            model_name='medicion',
            name='estacion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion'),
        ),
    ]
