# Generated by Django 4.1.7 on 2023-03-13 17:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_medicion_id_estacion_medicion_estacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='contacto',
            name='localidad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='partido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
