# Generated by Django 5.0.1 on 2024-01-31 17:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_estacion_desde_alter_estacion_fuente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_inicio', models.DateField()),
                ('ultima_coneccion', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='hasta',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='estacion',
            name='descripcion_lugar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='estacion',
            name='id_externo_estacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estacion',
            name='numero_serie',
            field=models.CharField(default='No tiene', max_length=35),
        ),
        migrations.AddField(
            model_name='estacion',
            name='ultimo_mantenimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='fuente',
            field=models.CharField(default='No se sabe', max_length=25),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='latitud',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='longitud',
            field=models.DecimalField(decimal_places=12, max_digits=15),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='estacion',
            name='estado_mantenimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estadomantenimiento'),
        ),
        migrations.CreateModel(
            name='EventoOcurrido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
                ('id_evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionAnemometrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_velocidad', models.DecimalField(decimal_places=3, max_digits=5)),
                ('validacion_velocidad', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionBarometrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_presion', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_presion', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionBateria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_bateria', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_bateria', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionConductividad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_conductividad', models.DecimalField(decimal_places=13, max_digits=15)),
                ('validacion_conductividad', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionDireccionViento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_direccion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('validacion_direccion', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionFreatimetrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_presion', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_presion', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionHumedad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_humedad', models.DecimalField(decimal_places=3, max_digits=5)),
                ('validacion_humedad', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionLimnigrafica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_nivel', models.DecimalField(decimal_places=4, max_digits=6)),
                ('validacion_nivel', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionPH',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_ph', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_ph', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionPiranometrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_radiacion', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_radiacion', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionPluviometrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_precipitacion', models.DecimalField(decimal_places=4, max_digits=6)),
                ('validacion_precipitacion', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionPuntoRocio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_punto_rocio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('validacion_punto_rocio', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionTemperaturaAtmosferica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_teperatura', models.DecimalField(decimal_places=4, max_digits=6)),
                ('validacion_teperatura', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionTemperaturaDelCurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_teperatura', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_teperatura', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionTurbidimetrica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_turbiedad', models.DecimalField(decimal_places=5, max_digits=7)),
                ('validacion_turbiedad', models.BooleanField()),
                ('tiempo_de_medicion', models.DateTimeField()),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_perm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.permiso')),
                ('id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('descripcion', models.TextField(default='')),
                ('ultimo_mantenimiento', models.DateTimeField()),
                ('estado_mantenimiento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estadomantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='EmaSensor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_ema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.estacion')),
                ('id_sensor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='InformeMantenimientoEstacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('descripcion', models.TextField(default='')),
                ('id_sensor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.sensor')),
                ('id_usr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.rol')),
                ('id_usr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicion',
        ),
    ]
