# Generated by Django 5.0.1 on 2024-01-31 17:36

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_estadomantenimiento_evento_permiso_rol_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='localidad',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='partido',
            field=models.CharField(max_length=100, default=''),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ultimo_mantenimiento',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultima_coneccion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
