# Generated by Django 5.0.1 on 2024-01-31 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_contacto_email_alter_contacto_localidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ultima_coneccion',
            new_name='ultima_conexion',
        ),
    ]
