# Generated by Django 5.0.1 on 2024-03-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_tiempo_de_medicion_medicionanemometrica_fecha_hora_and_more'),
        ('myapp', '0027_tipousuario_usuario_activo_usuario_superuser_and_more'),
    ]

    operations = [
    ]
